# These are supported funding model platforms

github: [piestyx]
# No casual/donation-first platforms here to keep the tone research-focused.
# Patreon/OpenCollective/etc. could be added later if desired.

custom: ['https://github.com/sponsors/piestyx']
